### ISSUE TITLE
mysql_escape_string() is deprecated.

### ISSUE THREAD

**Issue by ozziest** [rogeriopradoj/codeigniter-composer#8]
Message: mysql_escape_string(): This function is deprecated; use mysql_real_escape_string() instead.

Filename: mysqli/mysqli_driver.php

Line Number: 320

**Comment by ozziest** [comment]
I think problem is 314. line. If $this->conn_id is false,  system trying to use mysql_escape_string() method. But mysql_real_escape_string() is available. My problem is a connection error.

**Comment by ozziest** [comment]
You can review original codes; https://github.com/bcit-ci/CodeIgniter/blob/2.2-stable/system/database/drivers/mysqli/mysqli_driver.php#L315

**Comment by rogeriopradoj** [comment]
Hello, @ozziest , sorry for taking so long.

I'm going to update project to latest v2.x., I think it will solve the problem, right? See ya.

**Comment by rogeriopradoj** [comment]
Fixed in d51fbe38f570172e1a973726c2aade28d2e5c9cc. Thanks for pushing me!
