### ISSUE TITLE
CodeIgniter 2.2.4 is out

### ISSUE THREAD

**Issue by royduin** [rogeriopradoj/codeigniter-composer#9]
Your current latest version is 2.2.0, please update the repository. See: https://github.com/bcit-ci/CodeIgniter/tree/2.2.4

Thanks!

**Comment by rogeriopradoj** [comment]
Hi, @royduin , thanks for getting in touch!

Could you send a pull request in order for helping me with this?

Thanks in advance!

**Comment by rogeriopradoj** [comment]
Fixed in d51fbe38f570172e1a973726c2aade28d2e5c9cc. Thanks for pushing me!

**Comment by rogeriopradoj** [comment]
T
